### ISSUE TITLE
radix_sort: failed to get memory buffer: out of memory

### ISSUE THREAD

**Issue by angervision** [Xtra-Computing/thundersvm#120]
Hello,

I have the following error during training phase:

```
2019-02-03 14:17:53,125 INFO [default] global iter = 0, total local iter = 2, diff = 2
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  radix_sort: failed to get memory buffer: out of memory
```

Here is my model, pretty basic actually:
```
clf = SVC(kernel='linear', probability=True)
clf.fit(X_train, labels)
```

Dataset size is:
- X_train: 512 dimensional array of 13320 elements
- labels: 3951 different labels (classes)

Machine configuration:

- **OS:** Ubuntu 16.04
- **RAM:** 16GB (+16 GB of swapfile)
- **GPU:** nVidia GTX1070 (8GB)

I've tried to adjust max_mem_size parameter with no luck (tried values 8192, 4096, 2048 and 2). Any ideas on how I can fix that?

Thanks!

**Comment by angervision** [comment]
> Can you share the dataset? So that we can try to reproduce the problem and debug it. The number of classes is very big in your case, which is a possible reason. It's hard to locate the problem without the dataset. Thanks.

Sure, here you can download the pickled dataset: [dataset.pickle](https://drive.google.com/file/d/1y2X7Otjzhy9S23fnEUqhZ8UxJw-LaCxl/view?usp=sharing)

You can load the dataset and use it in the following way:

```
import pickle
from thundersvmScikit import SVC

with open('dataset.pickle', 'rb') as infile:
    (X_train, labels) = pickle.load(infile)

clf = SVC(kernel='linear', probability=True)
clf.fit(X_train, labels)
```

P.S. Here is my memory usage during the run of the script above:

```
Every 2.0s: nvidia-smi                                                                                                                         Sun Feb  3 16:51:14 2019

Sun Feb  3 16:51:14 2019
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1070    Off  | 00000000:01:00.0 Off |                  N/A |
|  0%   55C    P2    34W / 166W |    141MiB /  8114MiB |     15%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     22883      C   python                                       129MiB |
+-----------------------------------------------------------------------------+
```

**Comment by GODqinbin** [comment]
Hi, @angervision . Since you set the "probability = True", there are two stages for the training: training binary models and performing probability train. Your log shows that the error happened in the first stage. However,  we tried the same dataset and but it worked fine in the first stage. The memory cost is small (<4GB) and your memory size is big enough. We cannot figure out why you failed yet. You can try to build and run ThunderSVM in CPU version, which may be faster than GPU in your case since the number of instances of each class is very small. 

For the second stage, there is a "std::bad_alloc" error when we train the dataset. Because the number of classes is really big, we need a lot of memory (>800G) to save predict values. We will try to improve it in the future. Thanks!
