### ISSUE TITLE
One-Class SVM showed out of host memory error

### ISSUE THREAD

**Issue by munhouiani** [Xtra-Computing/thundersvm#37]
Hi,

I used the CPU-only version to train a one-class svm with linear kernel using a very large, high-dimensional dataset (around 170GB with 3000 dimensions).

I ran my experiment on a 488GB ram, 64 cores AWS machine, with the following command:
```
./thundersvm-train -s 2 -t 0 -n 0.5 largedataset.libsvm largedataset.model
```

After half an hour, it showed 
```
FATAL [default] out of host memory
```

How to make it work? Can limiting the number of cores solve the problem?

**Comment by zeyiwen** [comment]
@mhwong2007 It's difficult for us to reproduce the problem, because we don't have the dataset and the machine with such large memory. A guess is that "-n 0.5" (meaning half of the training instances are support vectors) may be too large for your dataset.

Would you please attach the full log for us to try to locate the issue? Alternatively, you can use publicly available datasets to produce the issue again, and then we can debug the code.

**Comment by mhwong2007** [comment]
I will try using a smaller `-n` option

I accidentally deleted the log, but it only mentioned:

```
FATAL [default] out of host memory
```

and error in `thundersvm-train` line 97

**Comment by shijiashuai** [comment]
@mhwong2007 The problem comes from dataset loading. I've just pushed a new version. You may try it to see whether your problem has been solved.

**Comment by mhwong2007** [comment]
Problem still exists...
Here is the log
```
2018-01-15 07:18:40,994 INFO [default] loading dataset from file "/dev/xvda9/scaled.libsvm"
2018-01-15 07:56:21,231 INFO [default] #instances = 3000000, #features = 3000
Segmentation fault (core dumped)
```

I used this command to build a linear one class svm 
```
./thundersvm-train -s 2 -t 0 -n 0.1 scaled.libsvm largedataset.model
```
